### ISSUE TITLE
Bourbon directory structure has changed

### ISSUE THREAD

**Issue by joshwalsh** [d-i/baseline#7]
The Brocfile looks for Bourbon here:

`bourbon = 'bower_components/bourbon/dist',`

But, there isn't a `dist` directory.  I believe it should be looking at `bower_components/bourbon/app/assets/stylesheets`

**Comment by bdielman** [comment]
This is a problem with any repo that has a `bower.json` file set to the latest version. We need to lock the version in for both Bourbon and Sass until we have time to test.
