### ISSUE TITLE
Updated SASS version required

### ISSUE THREAD

**Issue by joshwalsh** [d-i/baseline#8]
A Bourbon update earlier this week now requires the latest version of LibSass (3.4.10).  Otherwise Bourbon will not compile:

`Syntax error: Invalid CSS after "@if ": expected expression (e.g. 1px, bold), was "& { "`

See fix here: https://github.com/thoughtbot/bourbon/issues/591

Consider adding a version requirements to the sass gem to be >= 3.4.10

**Comment by joshwalsh** [comment]
https://github.com/d-i/baseline/blob/master/Gemfile.lock#L4

**Comment by bdielman** [comment]
We're installing Bourbon via Bower for this repo, not as a gem.

**Comment by bdielman** [comment]
Version 3.4.10 of Sass is referring to the Ruby version, not LibSass which is at 3.1.0 at the moment. An updated version of Bourbon (4.2) will support both Ruby and LibSass so we will update Baseline to work with that version.

**Comment by bdielman** [comment]
This issue was fixed with commit c1b97b3.
